showWidget({
    wid: 'html',
    data: 'Secondary structure calculations '
}).then(lb => {
    let progressBar;
    let w = {
        wid: 'progress',
        componentRef: 'progressBar',
        data: {
            'progress': 10,
            'progressBar': createIonFunction((progessBar) => {
                progressBar = progessBar;
            })
        }
    }
    showWidget ( w );

    let engineMonitor = new EngineMonitor((msg) => {

        console.log ( " progress " + msg )
        lb.setHTML(msg)
    });
    engineMonitor.addProgressListener(async (v) => {
        progressBar(v);
    })

    exec('py/baja/secondary-structure/energy-window.py', engineMonitor, 'AGGTAGCTGCGTGGCTAACGGAGAAAAGAAGCCGTGGCCGCGGGAGGAGGCGAGAGGAGTCGGGATCTGCGCTGCAGCCACCGCCGCGGTTGATACTACTTTGACCTTCCGAGTGCAGTGGTAGGGGCGCGGAGGCAACGCAGCGGCTTCTGCGCTGGGAAATTCAGTCGTGTGCGACCCAGTCTGTCCTCTCCCCAGACCGCCAATCTCATGCACCCCTCCAGAGTGGCCCTTGACTCCTCCCTCTCCTCACTCCATCTTTCCTGGCCTCTCTCCGGGTGCTTAGCGGACTTGGCCAATAACCTCCTCCTTTTAAACGCCCTGAATTGAACCCTGCCTCCTGCGCATCCTCTTTTTGTGTCACCTTAGGGTTCAGATTTAACTACGCGACTTGACTAGTCATCTTTTGATCTCTCTCTCGTATTTAGTACTTTTAGTCAGCGAGCATTTATTGATATTTCAACTTCAGCCTCGCGGTTAAGAGCTTGGGCTCTGGAATCATACGGCTGGAATTGGAATTCTGTCAGTCGTGTGGCCGCTCTCTACTGTCTTGTGAAGATAAGTGAGATAATCTTGACCTGTGGTGAGCACTCGTGAGCGTTAGCTGCTGTATTTACCAGGTACAGATAAGACAACTACAGTGGATGATAATGTATGTGGTGATAGGGGAGTACTCTGATGGTAGAGGAGTGACTTTGGTTCTCTGCAAACTCAGCCTGAGACTATCAATTCAGTTTGTGGTGAGACCTCGCAGTGTTACCTTGGCAGATGGTAGAAGCCTTCCAGATGGAAGGAAAAATGCGTGTAAAGGCACAAAGTGTAGAAGGACCCTGAAGCTCCAGCGTGAGGCCTGGCATTGAATGAAATATATTTTGTGGGTTTTCAGCTGCTGAAGTCATAGGAATGGATGAGACCAAGAAAACAAAGCTGTTTTTGAGGTATGAGCGGAAGAAGAGATATCAGGAGACTTTCGAAACAGTCATAACGGAAGTTAATATGATCATTGCTAACATTTGCTGTGTTTCAGGCACTGTAAGCATGTATATGGGTCCTTAAAGGGACTCATAGAGGTAGGTACTAGTATTGTTTTTCCTTTTATCATTGAGAAACTGAGGTTTGAAGAGATTAGTGAACTTGCTCTAGATTATACAGTTTGTAAGTGGCTGAACCAGGATTTGAACTAATACAATCTGACTACAGAGGCCACACTCCTTAGCACTAGAAAAGAATGGCATGCCAAGGGCAGAGTTATTTCTAGGAAGATGGGATATAAGCGTCATTGTCAAGTTGTG').then(r => {

        showWidget({
            wid: 'json',
            data: JSON.stringify(r)
        })

    })
})
