from Levenshtein import distance
from ion import works
from Bio.Seq import Seq
from Bio.Align import PairwiseAligner
import json 
import traceback
import sys


try: 
    # target = works.param (1)
    
    target = "TCATTGCAACCTCCGCCTACTGGGTTCAAGCAATTCTCCTGCCTCAGCCTCATGAGTAGCTGGGACTATAGGCGCACGCTGCCACGCCCGGCTAATTTTTTGTATTTTAGTAGAGGCGGGGTTTCACCTTGTTGACCAGACTGGTCTTGAACTCCTGAGCTCAGGCAGTCCGCCCGCCTCGGCCTCCCAAAGCGTTGGGATTACAGGCGTGAGCCACTGCACCCAGCCAAATATACTATTCTTAACGCTAAATGTCCTAAGTAGATATAACTGTCCCCATTTTAGAGATGAGGAAATTCAGGTACAGATAAAGTCACTTAACAGTGCACACAAGTGGTAAGGCTGGAATTCAAACTCAGGCTTCTCTGGCTCCAAAAGGCTGAGCTCTTCATTAGACCAGTCCCCTTGCCCCTCGATGCCCTGTGTAACCCACTAGAAGAGTGGGTAGGAGGAAAGCCATCAATCCCGGAGCACCAGGGAGACACACGAAAGGCCCAGACTCCGGGACTGAAGAACTCCTGCTGACAAAAATAGTTATAAACATTCCTGTCCATTTGGGATCATTGTGGGTTGGTATTAGAACAAGCTGGACATCCTAATGTTCCAGGCAAGCAGAAGCTCTCTGCTTCAGACCATATACTTTCTAATAATGTAACTAGCCAAAGCTAGTCATAAAAATTCTGAATCACTGGTCAAGAAACACATTTTCTCATCATCCCCTCTATAGCCACCCCTCCAACATTTTCCCCTGATGATTGAATTCTAAGGTTCCCTCACCCCTGCTTTTCTCTGCCAGGGGATGAAGTGAGTAGAAGGAGGCTTTGTCTAAGGACTGTGACTCCTCTTACCCTCTCACTGCACTCAGCAGCCCGAGAGGTGAGTTCAGGCATCATCCACTTAGCTCTTCTAGGGCCAAATTATAAGTGGAAAGCAGGAGAGATCAGAGGTGCCAGACTCAGTCTATGAAAGACAGATACTCCTCTTTTTCCTCAATCTCCCTCACTAATCCCCACCCCCCCAAATAAATACACTGACAAAGCGTTGAAAGTTGCACTTTCCAAGTCAATTCAGTCTCTCTTATGAAGTGGCTTCAGTATTTATCAGGTTATAGATTATGATCAATTGGTCTGAACTTTGAATCTAAATCTAAAAATTATTGCTTTGCTTCGAATAAAACTAATAATAAAAACTAAATCTATTGATCACTTATTAGGTGCCAGACACTGTCCTAGGCATGTCGTATGTTGTCATTTAATCTTCAAAAAGATCCCATGAGTTACTCTCATTAGTCTTCTTTTACTCTAAGGAAACAGAGGCTGAGAGAGTTTAGGATAATTCCACAAGGTTATCAATTTGTCGTTATAATGTTTGTATGTATGTATGTATGTATGTATTATTTTGAGACAGAGTCTTGCTCTGTCTCCCAGGCTGGAGTGCAGTGGCACAATCTTGGCTCACTGCAATCTCCGCCTCCCGGGTTCAAGTGATTCTTCTGCCTCTGCCTCCCGAGTAGCTGGGATTACAGGCGTGTGCCACCACGGCTGGCTAATTTTTGTATATATGTATATATTTTAGACGGGGTTTCGCCATGTTGGCGAGGCTGGTCTTGAACTCCTGACCTCAAATGATCCACCCACCTTGGCCTCCCAAAGCGCTGGAATTACAGACGTGAGCCACCGCCCCAGCACTGTTGTTATAATGTTTTAGTAACTAACATTTACATCACATCAACAAGTGCTAAACACTAAACTAAGTGCTTTGTGTATGCTAACTTGTTGAATGTCTATAGTTACCCTGTAAGAGAGGTGTATTCCCTGCGCTTTATGGATGAGAACATTGAAGTCAGGTGAGGAATGTGCGCTAGGTCCCATAGGTGAGAATAGGCAGATGCAGGATTTGGACCCTGGTAGTTTGGCTGGAGCATCAGTCTTAATCTCAACACCTGTCTTCTCAGATTTGGATTCTGGCTCACGGGCTGCAGAGCCTGTACTTCTTTTTTTTTTCTTTTTCCCAGAGACAGGTTTCTGTTGCCCAGGCTGGAGCACAGCGGCGCAATCATAGCTCACTGCAACCTCAACCTCCTGGGCTCAAGCAATCCTCTTGTCTCAGCATCCCAAGTAGCTGGGACTACAGGCATGCACCACCATGCTCAGTTAATTAAAAAAAAAATTTTTTTTCCTTCAAGACGAAACCTCGCTCTGTCACCAGGCTAGAGTGCAGTGGTGCGATCTTGGCTCACTGCAACCTCTGCCTCCCGGGTTCAAGCAATTCTCTTGCCTCAGCCTCATGAGTAGCTGGGACTACAGGCATGTGCCACTACGCCCAGCTAATTTTTTGTATTTTTAGTAGAGATGGGGTTTCACCATATTGGTCAGGATGATCTTGATCTCTTGACCTTGTGATCCACCTGCCTTGGCCTCCAAAAGTGCTGGGATTACAGGCGTGAGCCACCGCACCTGGCCAATTTTTAAAAATTTTTAGTAGAGATGAGGACTCACTATGTTGTCCAGGCTTGTCTTGAACTCCTGAGCTCAAGTGACCCTCCCGTCTCAGCCTCCCAAAGTGCTAAGATTACATAGAGCCTATATTCTTAACCTCTCTTCCTTGGTTTTTGATACTTGAAAATATTTTTTCCCTAAATTTTTCCAAAAATGTACAGGATCCAAGTGGCAGACAGGTCCTCCGGATTCTATTCCGGGTTCTGTCCCTGACTCATGGGTGACACTGGGTAAGTCACAACTCTGCCAACAAGACACTGAAACTTGCACTTTCCCTCTACTAATTATTTAATGTACTGCAAATCCTGCTTGACCTTAAGTACAGGAGAAATTTGACTTGTAAAAAGAGATAACTTAGGCCAGGCACAGTGGCTCAT"
    # query = "CGGCTAATTTTTTGTATTTTAGTAGA"    
    f = open("demofile.txt", "r")
    lines = f.readLines()
    for l in lines:
        print ( l )

    query = 'terst'


    ql = len(query)
    print ( ql )
    m = []
    for element in range(0, len(target)):
        t = target[element:element+ql]
        ldv = distance ( query, t )
        m.append ( {
            "i":element,
            "ld":ldv
        })

    mlist = (sorted(m, key=lambda i: i['ld']))
    nmlist = []
    for item in mlist:
        if item['ld'] < 5:
            nmlist.append (item)
        else:
            break

    # print(nmlist)
    works.resolve (nmlist)

except Exception:
    traceback.print_exc() 
    works.resolve({'results':'exception'})

