import joblib
import pandas as pd
import re
import numpy as np
import json
import os
import ast
# Display results
import pandas as pd
import re
import numpy as np
import joblib
import pandas as pd
import re
import numpy as np
import json
import os
import ast
# from ion import works

import joblib
import pandas as pd
import re
import numpy as np
import json

# Load the trained model
clf = joblib.load('../ljlapps/py/ml/dilution_series_model.pkl')

# Function to convert string data to an array
def convert_to_string_array(string_data):
    try:
        if string_data.startswith("[") and string_data.endswith("]"):
            string_data = string_data[1:-1]
        parsed_list = [item.strip().strip('"') for item in string_data.split(',')]
        return parsed_list
    except Exception as e:
        print(f"Error parsing string: {e}")
        return []

# Function to extract numerical features from a sequence
def extract_features(sequence):
    values = []
    for item in sequence:
        num = re.findall(r'\d+(?:\.\d+)?', item)
        if num:
            values.append(float(num[0]))
    
    if len(values) < 2:
        return [0, 0, 0], []  
    
    ratios = [values[i] / values[i+1] if values[i+1] != 0 else 0 for i in range(len(values) - 1)]
    mean_ratio = np.mean(ratios) if ratios else 0
    std_ratio = np.std(ratios) if ratios else 0
    min_ratio = min(ratios) if ratios else 0
    
    return [mean_ratio, std_ratio, min_ratio], values

# Function to predict dilution series
def predict_dilution(sequence):
    features, extracted_series = extract_features(sequence)
    prediction = clf.predict([features])[0]
    return {"sequence": sequence, "predicted_class": int(prediction), "extracted_dilution_series": extracted_series}

# Test data
# test_data = [
#     "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "395254", "141923", "676630",
#     "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "5201", "582468",
#     "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "5198", "5199",
#     "STD100", "STD50", "STD25", "STD12.5"
# ]
test_data = [
            "A1",
            "A1",
            "A2",
            "A2",
            "A3",
            "A3",
            "A4",
            "A4",
            "A5",
            "A5",
            "A6",
            "A6",
            "A7",
            "A7",
            "A8",
            "A8",
            "A9",
            "A9",
            "395254",
            "395254",
            "141923",
            "141923",
            "676630",
            "676630",
            "B1",
            "B1",
            "B2",
            "B2",
            "B3",
            "B3",
            "B4",
            "B4",
            "B5",
            "B5",
            "B6",
            "B6",
            "B7",
            "B7",
            "B8",
            "B8",
            "B9",
            "B9",
            "B10",
            "B10",
            "5201",
            "5201",
            "582468",
            "582468",
            "C1",
            "C1",
            "C2",
            "C2",
            "C3",
            "C3",
            "C4",
            "C4",
            "C5",
            "C5",
            "C6",
            "C6",
            "C7",
            "C7",
            "C8",
            "C8",
            "C9",
            "C9",
            "C10",
            "C10",
            "5198",
            "5198",
            "5199",
            "5199",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "UTC",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "STD100",
            "STD100",
            "STD100",
            "STD50",
            "STD50",
            "STD50",
            "STD25",
            "STD25",
            "STD25",
            "STD12.5",
            "STD12.5",
            "STD12.5",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "TE",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*",
            "*"
        ]




results = [predict_dilution(test_data)]
df_results = pd.DataFrame(results)
results_json = json.dumps(results, indent=4)

print(results_json)
